name: 'dotnet restore'
description: 'dotnet restore'
inputs:
  path:  
    description: 'path'
    required: true
  newTag:  
    description: 'newTag'
    required: true
  temp_path:  
    description: 'temp_path'
    required: true
  build_configuration:
    description: "build configuration"
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
        cd "${{ inputs.path }}"
        Get-ChildItem -Path .\ -Filter ${{ inputs.file_extenstion }} -Depth 1 -Recurse -File -Name| ForEach-Object {             
            dotnet publish --configuration ${{ inputs.build_configuration }} --output "${{ inputs.temp_path }}/LMI" /property:Version=${{ inputs.newTag }}
        }
      shell: powershell